### PR TITLE
Add Dark mode support 

### PR DESCRIPTION
**Pull request by swetasingh8844**
this is what  i have changes 
image
Issue #62

### CODE REVIEW

**Comment by janvi01** [comment]
@prash240303 would you be reviewing this?

**Comment by prash240303** [comment]
looks good to me @janvi01 merge it ?

**Comment by swetasingh8844** [comment]
@janvi01 my points are not added in leaderboard. please check it

**Comment by janvi01** [comment]
can you recheck? 

> @janvi01 my points are not added in leaderboard. please check it

**Comment by swetasingh8844** [comment]
I checked but still the points are not added. It seems that the issue is not closed yet, maybe because of that. please check it

**Comment by prash240303** [comment]
i hope it doest now ,

**Comment by swetasingh8844** [comment]
Ya now it's showing . Thank you

**Pull request merged**
