### PR TITLE
Add import button

### PR DESCRIPTION
**Pull request by Yogeshp0012**
Description

- Added the import button

Screenshot

image

### CODE REVIEW

**Review by janvi01 — CHANGES_REQUESTED** [review]
Thanks for the PR @Yogeshp0012. Kindly make these changes.

- Look at the [issue description](https://github.com/janvi01/sql-editor/issues/8#issue-1938367475) where you have to add the import btn in the UI. You have added in the navbar (definitely strange if you have sense). 

- Add issue number in the pr.

- Add onclick functionality on the btn that prompts the user to their local files.

**Comment by Yogeshp0012** [comment]
Resolves [Issue #8](https://github.com/janvi01/sql-editor/issues/8)
@janvi01 Made the changes.

**Comment by janvi01** [comment]
@Yogeshp0012 The PR LGTM, but we need one more change. You have added the import button in the wrong file. The `QueriesDrawer.js` file is for the table's side navigation drawer. Kindly add your code(import button) in `EditorBottomControls.js` after line 24.

**Review by janvi01 — CHANGES_REQUESTED** [review]
@Yogeshp0012 The PR LGTM, but we need one more change. You have added the import button in the wrong file. The `QueriesDrawer.js` file is for the table's side navigation drawer. Kindly add your code(import button) in `EditorBottomControls.js` after line 24.

**Comment by janvi01** [comment]
@Yogeshp0012 any updates?

**Comment by Yogeshp0012** [comment]
Done @janvi01. QueriesDrawer.js has only formatting changes.

**Comment by janvi01** [comment]
LGTM @Yogeshp0012 Which formatter are you using in your ide? The project uses https://prettier.io/

**Review by janvi01 — APPROVED** [review]

**Pull request merged**
