### PR TITLE
Feat: Add Sigle History Delete #9

### LINKED ISSUE #9: Feat: Add a single history delete functionality
**Is your feature request related to a problem? Please describe.**
Currently, the user is able to delete all history at once. There should be a way to delete a single history at a time.

Screenshot 2023-10-12 at 12 20 45 PM

**Describe the solution you'd like**
Add a delete button beside each history row and onclick it should delete that particular history. This can be done using a map and assigning a unique key to every history.

### PR DESCRIPTION
**Pull request by killerkc12**
**Description**

- When we click on the Delete icon, we filter out the History State and update the state with all other history other than the current history item.
- Please review the code. I've updated some UI in the History List because the Delete button was moving to the other line. Please let me know about this
The video is attached below

https://github.com/janvi01/sql-editor/assets/50802786/a01dbe0f-18bd-481b-8b3d-41797e212692

**Related issue(s)**
Fixes #9

### CODE REVIEW

**Review by janvi01 — CHANGES_REQUESTED** [review]
Thanks for the PR. @killerkc12 Well done. Kindly make the required changes-

- When we delete a single history query, the editor text changes to that query.
(the editor query should change when we click on the box of single query history, not also when we click on delete btn.)

**Comment by killerkc12** [comment]
@janvi01 Got you. I will make the changes and let you know.

**Comment by killerkc12** [comment]
@janvi01 I've did necessary changes, please check the video.

https://github.com/janvi01/sql-editor/assets/50802786/421e7f55-b46b-4471-8232-0bdbf536b8ad

**Review by janvi01 — APPROVED** [review]
LGTM, well done.

**Pull request merged**
